name: yocto-container build and test
on:
  push:
    branches:
      - master
  pull_request:

  # Allow for manually running
  workflow_dispatch:

  # Run at 00:52 UTC every Saturday
  schedule:
    - cron: '52 0 * * 6'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        distro_to_build: [
          alma-8,
          alma-9,
          centos-7,
          debian-9,
          debian-10,
          debian-11,
          fedora-34,
          fedora-35,
          fedora-36,
          opensuse-15.2,
          opensuse-15.3,
          opensuse-15.4,
          ubuntu-18.04,
          ubuntu-20.04,
          ubuntu-22.04
        ]
        targetplatform: [
          linux/amd64
        ]
    env:
      DISTRO_TO_BUILD: ${{ matrix.distro_to_build }}
      REPO: $${{ vars.REPO }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cp build-install-dumb-init.sh install-buildtools.sh install-buildtools-make.sh dockerfiles/${{ matrix.distro_to_build }}

      - uses: docker/build-push-action@v4
        with:
          context: dockerfiles/${{ matrix.distro_to_build }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.REPO }}:${{ matrix.distro_to_build }}-base
            ghcr.io/${{ vars.REPO }}:${{ matrix.distro_to_build }}-base

      - run: |
          mv dockerfiles/templates/Dockerfile.builder dockerfiles/templates/Dockerfile
          cp distro-entry.sh helpers/runbitbake.py dockerfiles/templates

      - uses: docker/build-push-action@v4
        with:
          context: dockerfiles/templates
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
              REPO=${{ vars.REPO }}
              DISTRO_TO_BUILD=${{ matrix.distro_to_build }}
          tags: |
            ${{ vars.REPO }}:${{ matrix.distro_to_build }}-builder
            ghcr.io/${{ vars.REPO }}:${{ matrix.distro_to_build }}-builder


